### ISSUE TITLE
[Feature] The survey list loads next page without threshold

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nyinyihtunlwin-codigo/nimble-survey#11]
In the context of pagination, the survey list loads the next pages immediately when the user visits the app. To improve the UX with lazy loading, please configure a threshold so that the next pages load when the user swipes to the end of the list.

https://github.com/nyinyihtunlwin-codigo/nimble-survey/assets/6950766/b20bca93-ddd5-452a-981f-b7eb8fcb3d95

**Comment by nyinyihtunlwin-codigo** [comment]
I've updated the pager configurations not to load all pages at once.
I've updated my code and merged in this [pull request](https://github.com/nyinyihtunlwin-codigo/nimble-survey/pull/17).
Please kindly check and let me know if anything needed. Thanks.
