### ISSUE TITLE
[Chore] Increase test coverage for the application

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nyinyihtunlwin-codigo/nimble-survey#13]
In term of testing, there is lack of UI instrumented test for screens, the UI code that also need to be tested 😄 Please setup and add UI test, a single screen test is adequate.

**Comment by nyinyihtunlwin-codigo** [comment]
I've added UI test for Login Screen.
I've updated my code and merged in this [pull request.](https://github.com/nyinyihtunlwin-codigo/nimble-survey/pull/18).
Please kindly check and let me know if anything needed. Thanks.
