### ISSUE TITLE
[Question] Curious about the nested component without a container

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nyinyihtunlwin-codigo/nimble-survey#9]
I am curious about this block of code. Do you have any intention behind wrapping `DetailsLoadingContent` with `SurveyDetailsLoading` without a container?

https://github.com/nyinyihtunlwin-codigo/nimble-survey/blob/3a42ba4f267e0221fbfd3ec0d381c9887c4054e7/feature/home/src/main/java/com/nyinyihtunlwin/home/components/SurveyDetailsLoading.kt#L30-L32

**Comment by nyinyihtunlwin-codigo** [comment]
For the future scalability which in case we might need to add more logic or UI components to **SurveyDetailsLoading()** without affecting **DetailsLoadingContent()**. As it doesn't seem necessary in this app, I will refactor that part.

**Comment by nyinyihtunlwin-codigo** [comment]
I've updated and merged in this [pull request](https://github.com/nyinyihtunlwin-codigo/nimble-survey/pull/15).
Please kindly check and let me know if anything needed. Thanks.
